---
- name: Windows Update
  hosts: windows_server
  gather_facts: true
  tasks:
    - name: Installation des mises à jour Windows Server (Sécurité & Critiques)
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates']
        reboot: yes